### ISSUE TITLE
Pure render functions with recompose HOCs vs Classes

### ISSUE THREAD

**Issue by jkaipr** [rainforestapp/frontend-conventions#19]
@rainforestapp/frontend
Paul posted a video from Michael Jackson 🕺  about never writing another higher order component into our slack channel https://www.youtube.com/watch?v=BcVAq3YFiuc, asking if we've seen it and what do we think about it.

Hamza replied:

_I think I concur and felt the same about HOC after using them a while.
They allow you to statically compose behaviour that can inherently be dynamic and feels a bit weird. I am all in for pushing abstraction at the react level more for most places we would use hoc's instead._

I replied:

_His points make sense and I can certainly see the render prop approach being useful in certain cases, but I’m not sure I’m entirely convinced I shouldn’t ever write / use another HOC.
Using of ES6 classes has some drawbacks http://blog.krawaller.se/posts/5-reasons-not-to-use-es6-classes-in-react/ which can be overcome by using next stage ES proposals https://michalzalecki.com/react-components-and-class-properties/ which is what he uses in his presentation.
He moved composition to the render function, so if we wan’t to get multiple shared functionalities into one component we would start building a jsx pyramid if I get it right?
Might be an interesting experiment to try converting some of our heavier components to this approach and see how it looks & feels.
I like that part that it’s clear where a property came from._

I mentioned it in my 1:1 with Adrian and we discussed it a bit. I will try to put it into points and would like to hear your opinions on this topic.

1. We never use ES6 classes to define components, we use recompose for everything. Even when we need local state, lifecycle and handlers. Maybe we should reconsider that, at least in some cases. If we add [babel preset stage 2](https://babeljs.io/docs/plugins/preset-stage-2/) to our codebase, we could have classes with syntactic sugar that makes their use easier, as described in the second link in my original reply cited above. It would probably improve readability + remove the nested functions from snapshots and react dev tools component tree view. (P.S. Let's just avoid inheritance)
2. We don't have to ditch recompose use completely imo, but limiting it's utilisation to reusable abstractions seems like a more reasonable use of it. Using it for everything is probably an overkill.
3. The render prop approach shown in the video seems fine, I'm not sure we should use it for everything, the way we use recompose for everything today, would feel like switching one dogma for another. Imo if we encounter an abstraction that seems like a good fit for it, let's use it. The only thing I dislike about this approach is if I imagine it being nested, it would make the render function grow a lot.

**Comment by ziahamza** [comment]
@jkaipr I think we already have examples of React component classes (with class properties) in our older codebase, and we moved away especially for a couple of good reasons:
- They dont support mixins. With classes, its not trivial  to de-compose a complicated class into multiple small classes and compose them together. E.g, here I use different HOCs depending on a prop: https://github.com/rainforestapp/regenwald/blob/develop/src/app/v2/components/TestList/WithState/index.js#L134
Doing something like this, and breaking down with React class based components is hard. 
- Class functions do not bind the functions by default, especially for event handlers. This is a pain, and very easy to forget. `withHandlers` are much easier, and work just fine. 
- There is no core replacement for `connect` from 'react-redux' / `withRouter` from 'react-router', 'DropTarget' from 'react-dnd'. The library support is much better for HOCs. 

The pros of classes over HOCs are:
- Flow Types work really well
- Snapshots are neater
- They are standard react. much easier to get started

Overall, I think we should build good abstractions, and expose them only as react components. that way it doesnt matter how its implemented, and you can use them just like any react components. I love the flexibility given by react `children` so we should pass down functions / arrays / whatever data structure makes sense to extend default react components to enable powerful abstractions. 

E.g. 
- move withFormState => a react component based abstraction
- use Flagged component, instead of featureFlag HOC whenever possible
- Prefer mapping / adding props in the render function instead of using `mapProps` / `withProps
- Create a react component with `withButtonState` like `Flagged` component.

**Comment by jkaipr** [comment]
@ziahamza I think you missed that I pointed out using stage 2 ES proposals, which allow you to do this:
```js
class Button extends React.Component {
  state = {
    clicked: false
  }

  onClick = () => { // class property can be an arrow function which binds this as expected
    this.setState({ clicked: true });
  }

  componentWillMount() {
    console.log("I'm a class without the need to bind handlers and initialise state in the constructor.")
  }

  render() {
    return <button onClick={this.onClick} />;
  }
}
```

As I tried to say in the original post, I don't have a problem with HOCs and I believe they are useful.

+1 to exposing abstractions as React components where possible/appropriate, it's much easier to read

**Comment by ziahamza** [comment]
@jkaipr we already have these 2 proposals already in our codebase: https://github.com/rainforestapp/regenwald/blob/39d8bfd1e6ef445e440ea5801c766139e2b1f64d/src/app/components/TestListMeta/FilterTestsBySearch/index.js#L13 
;)

yes, I guess using arrow functions by default would solve the bind issue. On a second look I agree that class syntax looks superior / simpler when in cases where `withStateHandlers` would be appropriate. 👍 for limiting HOCs when class syntax would work just fine (and preferably using react components to share logic / handlers).

**Comment by jkaipr** [comment]
@ziahamza Ah, I see now. I was only checking this part for `stage-2` and missed that it's installed separately as a babel plugin.

**Comment by ziahamza** [comment]
@jkaipr @rainforestapp/frontend Wrote how WithFormState would look like as a react class:
https://github.com/rainforestapp/regenwald/pull/3595

What do you guys think? I can finish off the PR if it looks good :)

**Comment by prayogoa** [comment]
One more thing that I'd be interested in is to make the react dev tool more readable, right now it looks like this with HOCs:
```
<hoc 1>
  <hoc 2>
    <hoc 3>
       <component that I render>
```

The problem here is that I need to dig deep to find the component that I'm interested in, but the meaningful behaviours are contained _outside_ of that component.

2 advantages of render prop over hocs:
- It's awkward to compose as many render prop components since you get the triangle of doom pretty quickly. This is a little tongue in cheek but I think it will force us to not cram too much functionality into a single component
- When looking at the dev tool, we will first find the component that we render, and then _inside_ that component we can find the render prop components that we use for shared behaviour eg.
```
<the component that I render>
  <render prop 1> 
    { propFrom1 =>
       ...
       <render prop 2>...</>
    }
  </>
  <render prop 3>...</>
</ the component that I render
```
I think this is more inline with how we would reason about components

**Comment by prayogoa** [comment]
also check out https://github.com/acdlite/recompose/pull/531

**Comment by jkaipr** [comment]
@ziahamza I like what I see in that PR, how do you feel about it?

**Comment by prayogoa** [comment]
What do you think of imposing the following rule for reducing hoc abuse:
When using hoc to reduce the boilerplate of using classes, only one single hoc is allowed. If more than one hoc is needed then use a class instead.

Example:
- needing state and handlers -> use 1 `withStateHandlers`
- needing lifecycle method only -> use `lifecycle`
- needing state / handlers and lifecycle -> class
- needing state and handlers, where one handler is called from another handler -> requires composing `withHandlers`, so use a class instead

**Comment by prayogoa** [comment]
Still unclear on where things such as `withProps` and `branch` would fit in this rule

**Comment by ziahamza** [comment]
@prayogoa I would prefer to move the `branch` / `withProps` / `mapProps` to the render function, unless they are required to use in conjunction with other HOCs (like `withButtonState`)

**Comment by prayogoa** [comment]
Tangent: I think we should just bite the bullet and refactor withButtonState...

**Comment by jkaipr** [comment]
Was curious how the difference between using `withStateHandlers` and a class looks like, made me write down an example:

```js
class Button extends React.Component {
  static defaultProps = { initialCount: 0 }; 
  static state = { count: this.props.initialCount }; 

  increment = () => this.setState({ count: this.state.count + 1 });
  decrement = () => this.setState({ count: this.state.count - 1 });

  render() {
    return (
      <div>
        {this.state.count}
        <Button onClick={this.increment}>Inc</Button>
        <Button onClick={this.decrement}>Dec</Button>
      </div>
    );
  }
}
```
vs
```js
const CounterView = ({ count, increment, decrement }) =>
  <div>
    {this.state.count}
    <Button onClick={increment}>Inc</Button>
    <Button onClick={decrement}>Dec</Button>
  </div>;

const Counter = withStateHandlers(
  ({ initialCount = 0 }) => ({ count: initialCount }),
  {
    increment: ({ count }) => () => ({ count: count + 1 }),
    decrement: ({ count }) => () => ({ count: count - 1 }),
  }
)(CounterView);
```

Some lines are saved, not much though. Thinking about this further, having different ways how to do things forces devs to know more APIs and to decide when to use what and refactor between the two depending on how the components responsibilities change.

**Comment by prayogoa** [comment]
So the new proposed convention is to not use hocs for the purpose of reducing boilerplate, as that just introduces multiple ways of doing the same thing. Does this mean that we don't use recompose anymore? Is there an example of valid recompose usage under this rule?

**Comment by ziahamza** [comment]
I have 2 PRs as follow ups. I think general direction is to keep using HOCs that dont have decent alternatives, and choosing React Components whenever possible. I propose we should perhaps close this discussion, and open discussions for specific use-cases that the new convention doesnt accommodate.
