### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by prayogoa** [rainforestapp/frontend-conventions#27]
I was looking at https://github.com/rainforestapp/regenwald/pull/3700 which refactors the 'Feature' feature into a new convention in terms of folder structure and it occurred to me that we never had a proper discussion on what we want the new folder structure to be.

The issue is that right now the components folder contains everything, and it's unclear what a component really is given what we are putting in that folder. The idea is to make each component self contained and modular by putting the action / reducer / react components together. I believe the convention falls short in 2 places:
1. Not everything needs to be modular and reusable, reusable implies abstraction, while to make anything useful we need some concrete
2. A react component can use many reducer states and there is no clear primary state that this component belongs to, in this case which component folder should this component belong to?

From the discussions we had we know that we need at least 3 categories, which we will reflect in our folder structure:
1. Reusable components, which we call `Components`
2. Concrete components, these are what we rendered in our app's route and will compose many `Components`. We call these `Routes`
3. Anything to do with the application state, including reducers, actions, schemas, selectors, etc. We call these `Models`

I'm not so sure about calling 2 `Routes`, open to suggestion for a better name.
For 3, I chose the name `Models` because I thought this is a representation of the backend's models in the frontend. Think of Tests, Features, Run Groups, Folders, etc. However I find that we also need to store things that doesn't exist in the backend such as the notification state, so I think `Model` would be a poor choice for the 3rd category. What do you guys think about adopting https://github.com/alexnm/re-ducks? It seems to capture the third category well

**Comment by pscohn** [comment]
Re-ducks looks pretty close to what we were discussing - bundling up anything store related. I don't think we necessarily need to adopt it 100% but I like the idea, it's basically in line with what we were thinking. I don't have a problem with using the `Model` term for it even though it's not necessarily a backend model, but fine with changing to something better (though I'm not sure `duck` is an improvement ;)

Side note, the operations idea is kind of nice and might help us split up our actions, but I think it's not important to do right now and we can have a discussion about it later if we need to.

**Comment by prayogoa** [comment]
I like plural for the folder name and singular for the file names

**Comment by AJFunk** [comment]
Instead of `Routes`, I have seen them called `Containers`. Personally I think `Routes` is a good name though. I'm also ok with using `Models`, I think it makes sense even if it's not technically correct.

I like how re-ducks moves `types` into their own files as well. The idea of having files that only have the component is nice. It always feels messy to me when we have types in the same file.

**Comment by prayogoa** [comment]
Agreed on types, although in re-ducks they actually meant action types, so they're just strings. We can use them for flow types.

**Comment by pscohn** [comment]
I'm not sure about a separate file for flow types - what would these types be for? The routes/components should have their types next to the component, and depending on the component it might be overkill to have a separate file for them. And for actions, selectors, etc, we usually type them inline since they're smaller.

**Comment by jkaipr** [comment]
My opinion on naming:
1. `Components`
2. `Views` - If I look at how Rails approaches it's naming convention, I wouldn't be afraid to just call these `Views`. They are tied into routes, but they aren't routes, routes are defined in our `Routes.js` files and I would consider it confusing to find these files in a directory called `Routes`
3. `Models` - I don't have a problem with using models, although most of them reflect models from backend, we can have our own frontend models derived from the backend data. I would prefer having a singular folder name and a singular file name `Feature/FeatureActions.js`, the model name is `Feature` imho, not `Features`, but it's just a detail (Rails has singular model name `feature.rb` and plural table name `features`, makes sense to me since `feature.rb` class instance represents one feature. Our situations is not as straightforward, actions can be for both many features and a single feature, selectors can also return one or many features..)

I've met the ducks concept before, I've got it stored in a list of things to consider using / looking into more. The `re-ducks` repo links to the original idea description [repo](https://github.com/erikras/ducks-modular-redux) which links other implementations / helpers taking the same approach. It doesn't look like any of the implementations have very lively repos (is there nothing to fix / maintain / improve anymore or are they just dying?). The concept looks useful and reducing redux boilerplate sounds like a good thing to aim for.

While talking about this, I'm going to link one more library connected to actions https://github.com/wellguimaraes/actionware. I liked how it handles action statuses and eliminates referencing actions by string based types. But I never really got into studying it further / playing around with it.

**Comment by pscohn** [comment]
I like your view on Views. So, I guess we are moving back to MVC? :trollface:

**Comment by jkaipr** [comment]
Some food for thought
https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1.
https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346

**Comment by jkaipr** [comment]
Those articles give two more options to naming number 2: `Scenes` and `Screens`. Both avoid being the `V` in MVC lol.
They both have a somewhat similar approach to placing components shared by a certain part of the scenes/screens tree into the closest common parent directory which keeps components tied to a certain scope of the application, trying to avoid just one root components folder with everything that's shared.

**Comment by prayogoa** [comment]
re type file:
Route and components should have their typing next to them, I was thinking more about model (eventually record) typings, so the component prop types can use them when they want to specify that they expect eg. a test or a run group passed in through props

**Comment by ziahamza** [comment]
I like types as a standalone file. especially for data model types ... i.e type of a RunGroup/ RunGroup Element / Feature / Run ...

Defn agree on the whole `Routes` idea! And I suppose that we can keep it in hierarchy ... i.e the internal folder structure of Routes following the actual url that corresponds to that route. 

For Models, we could follow the redux store hierarchy.
