### ISSUE TITLE
Creating mock data in specs

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/frontend-conventions#28]
While we wait for the perfect mock store generator I thought we could at least make a convention to make setting up mocks for specs easier.

It's kind of a pain to put together a mock store for tests right now, as you have to figure out where the mock data lives - if there is any - and then figure out how to structure that inside a store object. And more often we just use fake shell objects with only the ID and maybe another essential property, and this is copied around the codebase. Ideally specs will never reference store shape and we can just import the data we need.

In the short term, we could have a couple ground rules:

1. Never put any mock data inside of a spec
2. Don't put mockData files near components or tests that use them (I can't think of a reason why this would be necessary, since all significant mock data is imitating the store). Instead put all mock data in a `ClientMockData.js` next to the reducer for that client/run group/whatever. e.g, `app/models/Client/ClientMockData.js`. Reuse whatever is in there and add to it when you need something different. 
3. Instead of inline mock data, pass in an object to createMockStore only with top level store keys, and generate the values with functions or constants from mockData.

Our mock store might then look like:

```
import { featureWithStar } from 'app/models/Features/FeatureMockData`;
...
    store = createMockStore({
      runGroups: runGroupsWithMultiplePages,
      features: featureWithStar,
    });
```

Pretty easy to implement and there will be one file per model with all the related mock data so we can reuse and expand during spec writing.

@rainforestapp/frontend

**Comment by ziahamza** [comment]
I definately agree that we need to consolidate the mock data and not go for arbitrary mockData @pscohn ! Some bugs are sometimes not caught, just because the mockData didnt cover the edge cases.

the `mockStoreGenerator` is now shipped, which pretty much abstracts away where mockData is stored, and how to compose them together. The main unknown now is where should the mockData be stored along with transforms that extend mockStoreGenerator. I agree that it should live next to the model itself. 

I have a proposed a convention to use `mockStoreGenerator` and extend that instead of directly using `createMockStore`. I can extend that proposal with any conventions we suggest here and bake those in as well:
https://github.com/rainforestapp/frontend-conventions/pull/29
