### ISSUE TITLE
On overuse of css module compose

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/frontend-conventions#35]
I think there are some cases when we overuse our composable css module helpers. The main pain point is finding/importing/using the correct helper when you can just write the css normally.

We can have a quick discussion on this so we're all on the same page for reviewing PRs and writing css.

Composable classes make most sense to me when abstracting some a hardcoded value that could change (though this is still annoying to use until we work with design to develop a common language):

- `margin-small`
- `font-size-large`
- any color

I find the helper is overkill/unhelpful when the value behind it doesn't change.

Examples (in helpers.css):
- `text-center`
- `justify-content-between`
- `overflow-hidden`

The values abstracted by these classes never change, and it's more work to use the class in a compose than to just use the plain css rules I know. Plus I think it's better generally to keep things vanilla when possible, to make things more readable and more easily portable if we ever move to something else.

There still might be situations where those classes might be useful, for example when an element doesn't have a dedicated css class but instead imports one helper as its class, or a few helpers and combines them using `classnames()`.

Thoughts?

**Comment by prayogoa** [comment]
There's a case for performance, because on build composed classes are simply expanded to concatenated strings. This combined with the fact that empty classes are pruned means we get lower bundle size and less css to parse.

That said, we don't necessarily need to optimize for performance, because I don't think we're bottlenecked by that.

I honestly don't have a good answer for this. IMO CSS convention has been the weakest part of our coding guideline so I'm really interested to hear what other people thinks about this

> or a few helpers and combines them using classnames().
For this I think creating a class and composing all the helpers is the way to go

**Comment by pscohn** [comment]
@prayogoa How does it result in lower bundle size? The difference in 10 instances of a class like `_text-nowrap_7hlqz_27` (just pulled this randomly from prd) and 10 instances of `text-wrap: none` seems negligible (or slightly larger) to me.

**Comment by prayogoa** [comment]
I typed up an example for this but chrome crashed and lost it :/

Because in code you don't actually hard code `_text-nowrap_7hlqz_27`, it's stored in a map like `{ classA: 'classA _text-nowrap_7hlqz_27' }`
So every time a class is reused / composed, there's some saving there.

Also since we remove empty classes, classes defined like this:
```
text-nowrap { text-wrap: none; }
.classA { composes: text-nowrap; }
.classB { composes: text-nowrap; }
...
.classZ { composes: text-nowrap; }
```

will become:
```
text-nowrap { text-wrap: none; }
```

Anyway I think we shouldn't be optimizing for performance right now since it's not the bottleneck. If composition helpers end up negatively impacting developer experience, then we should cut back on it

BTW the current convention of using very specific helper classes are loosely inspired by the [Atomic CSS](https://acss.io/thinking-in-atomic.html) approach

**Comment by jkaipr** [comment]
An idea about analysing css classes and extracting individual style declarations (lines) into helpers at build time was forming in my head while thinking about this problem. That way we wouldn't have to give up css bundle size and browser rendering speed optimisations and could have developers happy not having to look up / remember the names of all the helpers.

Bumped into this while thinking about it and googling around:

https://ryantsao.com/blog/virtual-css-with-styletron
https://github.com/rtsao/styletron

I'm aware we still have a cocktail of scss and css modules, so imagining a switch is hard. But seemed like worth sharing.

**Comment by ziahamza** [comment]
I would say that with CSS having it critical to have it be maintainable and readable compared to perf optimizations, as chances of it becoming our main bottleneck is very low. 

I would overall prefer full versions of `text-center` or `justify-content-between` as its standard CSS and composibility only alienates us into a foreign syntax that's not standard CSS for no added gain. 

I love composing styles together as a way to share styles, and it works really well espcially as we can granularity import from other CSS, so things like static values, or other non-trivial styles should land in there to improve upon things. So defn agree with @pscohn on limiting the use of `composes: ...` to non-trivial stuff.

**Comment by prayogoa** [comment]
Lets revisit this when we're done with RF1 deprecation

**Comment by prayogoa** [comment]
So a way to act on this is to audit our helpers and remove those we don't find useful. Afterwards, moving forward we should be more critical to additions to the helper classes when reviewing PRs
