### ISSUE TITLE
Proposal to stop using snapshot tests for "it renders"

### ISSUE THREAD

**Issue by prayogoa** [rainforestapp/frontend-conventions#38]
This discussion can also be titled `Stop writing "it renders"` tests

I was hesitant to propose this but the more I think about it, and [read](https://codeburst.io/a-place-for-jest-snapshot-testing-ca1fc737c457) [other's](https://blog.kentcdodds.com/effective-snapshot-testing-e0d1a2c28eca) [thoughts](https://engineering.ezcater.com/the-case-against-react-snapshot-testing) on it, I'm convinced this is a good idea.

The main motivator for me to stop doing it is because `it renders` produces giant snapshots that people will just blindly update without checking, and it's not out of laziness either. These giant snapshots hardly provide any value when they break.

To really provide value it is imperative that snapshot changes are reviewed in PRs. Giant snapshots won't be reviewed and they provide a false sense of coverage.

@rainforestapp/frontend Do you think "it renders" snapshots provide enough value to justify their bloat?

**Comment by jkaipr** [comment]
I would say it makes sense to do `it renders` for smaller sized components focused on doing one thing, but it becomes bloated and useless if you try to do one snapshot for the whole root component a route view. In those cases it would probably be better to only use `it renders ComponentXY` for individual parts of the complex view which is made out of many components (doesn't apply just for `routes` components, but I guess most of these big snapshots should be there, because that's where we assemble all the reusable building blocks).

I agree that the main pain is length of the snapshot. Sometimes we bloat things up by not looking for the first rendered node and snapshotting the whole HOC tree of the component, which can add many levels of repetition if some bigger prop is being passed through (e.g. mock client object), but even skipping that is sometimes not going to be enough to make the snapshot readable.

**Comment by pscohn** [comment]
I only had time to read one or two articles, but I still feel there's some value to do `it renders` tests. 

For small components with no logic, I think it's still better than having no tests or a simple render. For these types of components I do usually check the snapshot to make sure it looks correct, and there have been cases where a snapshot changed that I didn't expect and probably caught a bug or two I wouldn't have seen if there was no snapshot. 

For larger components with more logic, I agree the size of the snapshot can make it more difficult to review, but I think it's more important to review thoroughly when there are changes to snapshots, and for large first-time check ins it's ok to skim it and make sure it looks right (I'd say it's more the writer's responsibility to make sure it looks right for the first check in). As far as for test writing, I find it useful to have a base case snapshot and some conditional ones to be able to check the differences are correct and not have to put as much effort into querying the dom. I really like just setting up some state/props and checking a snapshot. Perhaps we can do more work to make these kinds of snaps smaller. 

I also think it's not too much trouble when a snap breaks, and I always check to make sure it's ok to update. If it's just some simple dom update, it's easy enough to update (and that's the only satisfying part of testing, easily making something go green). If it's something else, we can be sure to check it's an intentional change, and I've found sometimes it's not.

**Comment by joycechau** [comment]
Agree with @jkaipr and @pscohn that `it renders` snapshots are still useful for smaller components. It always makes me feel better even if there's just one test for a component, and I like to ensure that it looks correctly and that the correct props are being passed through.

For larger components especially those wrapped in a bunch of HOCs, the snapshots are bloated IMO and makes it difficult to read and for the most part I tend to glance over those and focus mainly on the actual components.

**Comment by AJFunk** [comment]
While I definitely think some of our snapshots are bloated with HOCs and can slimmed down, I think even the larger snapshots provide value mainly for two reasons:

1) They provide a base case. All of the conditional pieces of the component can be tested individually
2) They provide sanity checks. I think blindly updating snapshots, no matter how big, is 100% laziness. While it can be cumbersome and tedious sometimes, I have caught several small issues by reviewing snapshots. I almost always update snapshots last, and it forces me to do a final review and ask "is this REALLY what should be changing in this snapshot?"

I agree that reviewers don't really dig into the snapshot changes (and I don't really expect them to TBH). While I have seen the occasional issue caught in a snapshot, I think they are much more useful for the author overall.

**Comment by ziahamza** [comment]
Just to chip in, I was a bit niglectance with checking snapshots recently and @prayogoa noticed this snapshot, which actually caught a tricky bug that was hard to trace down (had to add Immutable List support in WithFormState): https://github.com/rainforestapp/regenwald/pull/4277#discussion_r207841879


I would personally vote for full snapshot coverage, but I agree that they are too big ... so we can have a limit, where instead of just one giant snapshot, we can snapshot different parts and state. I dont think I have caught an error in the big snapshots yet, but small snapshots that test different states are super helpful.

**Comment by prayogoa** [comment]
Yes I'm not suggesting removing snapshots altogether, just the giant ones.

We should still aim to fully cover code changes with tests, but we can write more, smaller tests that target specific parts of the component.

Another thing I'd suggest is to skip snapshots on static parts of the component, in that case there's no difference between checking the snapshot and checking the component code itself

**Comment by pscohn** [comment]
@prayogoa what do you mean by static parts of the components? For functional components with no logic, it's true that there's no difference between checking the code and the snapshot, but even then I would say there's a benefit to having the snapshot - it proves it actually renders what you'd expect, and if something unexpected changes that is included in the snap (maybe dependency it uses) it'll fail. I can't think of a specific example but I think this has happened, and it feels like a good sanity check even if the change is intended.

**Comment by prayogoa** [comment]
i don't mean `<div>{somethingFromProps}</div>`, but more like `<div>This is a literal string that will be exactly the same in the snapshot</div>`.

And for conditional strings we could have just used an assertion to match that string exactly.

Summarizing the discussion so far:
Snapshot tests are useful up to a point where they get too long and unwieldy to review effectively. We should still use them but limit the length a single snapshot can have. It's fine for small components to have whole snapshots, but for larger components the snapshots should be split up and target specific parts of the component.

Did I miss anything?
